version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: aurora
      MYSQL_DATABASE: riodevida
      MYSQL_USER: joaopedro
      MYSQL_PASSWORD: aurora
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
